name: LintHTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linthtml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run htmlhint
        run: yarn run htmlhint ./index.html
